version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram/udagram-frontend
            npm install
      - run:
          name: Install API Dependencies
          command: |
            cd udagram-api
            npm install
      - run:
          name: Front-End Lint
          command: |
            cd udagram/udagram-frontend
            npm run lint
      - run:
          name: Front-End Build
          command: |
            cd udagram/udagram-frontend
            npm run build
      - run:
          name: API Build
          command: |
            cd udagram/udagram-api
            npm run build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy Frontend & Backend
          command: |
            cd udagram/udagram-frontend
            npm run deploy
            cd ../udagram-api
            npm run deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
