version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udagram/udagram-frontend
            npm install
      - run:
          name: Install API Dependencies
          command: |
            cd udagram/udagram-api
            npm install
      - run:
          name: Front-End Lint
          command: |
            cd udagram/udagram-frontend
            npm run lint
      - run:
          name: Front-End Build
          command: |
            cd udagram/udagram-frontend
            npm run build
      - run:
          name: API Build
          command: |
            cd udagram/udagram-api
            npm run build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/setup

      # Deploy Frontend
      - run:
          name: Build & Deploy Frontend to S3
          command: |
            cd udagram/udagram-frontend
            npm install -f
            npm run build
            chmod +x bin/deploy.sh
            ./bin/deploy.sh

      # Build & Deploy Backend API to Elastic Beanstalk
      - run:
          name: Build Backend API
          command: |
            cd udagram/udagram-api
            npm install
            npm run build

      - eb/deploy:
          application-name: "udagram-api"
          environment-name: "udagram-api-dev"
          region: "us-east-1"
          label: "deploy-<< pipeline.number >>"
          path: "udagram/udagram-api/www/Archive.zip"

workflows:
  udagram:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
